### ISSUE TITLE
gatsby-remark-images-datocms not working with newest version of gatsby-source-datocms

### ISSUE THREAD

**Issue by wildpow** [datocms/gatsby-source-datocms#156]
Upgrading an existing project from version 2 to version 3 of Gatsby and `gatsby-source-datocms` from 2.3 to 2.6. Which made `gatsby-remark-images-datocms` stop working. I created an [issue](https://github.com/datocms/gatsby-remark-images-datocms/issues/5) on that repo but, the stack track indicates the problem may be with the source plug-in (also the remark plugin doesn't seem to be maintained as well as this is).

from GraphiQL 
```
  "stack": [
        "TypeError: Cannot read property 'forceBlurhash' of null",
        "    at _callee$ (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:76:34)",
        "    at tryCatch (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:63:40)",
        "    at Generator.invoke [as _invoke] (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:293:22)",
        "    at Generator.next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:118:21)",
        "    at asyncGeneratorStep (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:15:103)",
        "    at _next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:17:194)",
        "    at /Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:17:364",
        "    at new Promise (<anonymous>)",
        "    at /Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:17:97",
        "    at /Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:130:18",
        "    at _callee$ (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-remark-images-datocms/utils/replace.js:72:20)",
        "    at tryCatch (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:63:40)",
        "    at Generator.invoke [as _invoke] (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:293:22)",
        "    at Generator.next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:118:21)",
        "    at asyncGeneratorStep (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-remark-images-datocms/utils/replace.js:3:103)",
        "    at _next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-remark-images-datocms/utils/replace.js:5:194)"
      ]
    }
  ],
  ```

**Comment by wildpow** [comment]
Or just use Structured text like the cool kids. 👍

**Comment by stefanoverna** [comment]
Resolved on `gatsby-remark-images-datocms` side!
