### ISSUE TITLE
Image URL & ALT query returns null

### ISSUE THREAD

**Issue by joebentaylor1995** [datocms/gatsby-source-datocms#96]
HI there seems to be an issue with the API as when I now query any images for the src or alt attributes i get this returned:
```{
  "errors": [
    {
      "message": "Cannot read property 'defaultFieldMetadata' of null",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDatoCmsProject",
        "edges",
        0,
        "node",
        "featuredImage"
      ],
      "stack": [
        "TypeError: Cannot read property 'defaultFieldMetadata' of null",
        "    at resolve (/Users/joetaylor/Documents/www/ics/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/item/fields/file.js:32:31)",
        "    at resolveFieldValueOrError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)"
      ]
    },
    {
      "message": "Cannot read property 'defaultFieldMetadata' of null",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDatoCmsProject",
        "edges",
        1,
        "node",
        "featuredImage"
      ],
      "stack": [
        "TypeError: Cannot read property 'defaultFieldMetadata' of null",
        "    at resolve (/Users/joetaylor/Documents/www/ics/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/item/fields/file.js:32:31)",
        "    at resolveFieldValueOrError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)"
      ]
    },
    {
      "message": "Cannot read property 'defaultFieldMetadata' of null",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDatoCmsProject",
        "edges",
        2,
        "node",
        "featuredImage"
      ],
      "stack": [
        "TypeError: Cannot read property 'defaultFieldMetadata' of null",
        "    at resolve (/Users/joetaylor/Documents/www/ics/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/item/fields/file.js:32:31)",
        "    at resolveFieldValueOrError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)"
      ]
    },
    {
      "message": "Cannot read property 'defaultFieldMetadata' of null",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDatoCmsProject",
        "edges",
        3,
        "node",
        "featuredImage"
      ],
      "stack": [
        "TypeError: Cannot read property 'defaultFieldMetadata' of null",
        "    at resolve (/Users/joetaylor/Documents/www/ics/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/item/fields/file.js:32:31)",
        "    at resolveFieldValueOrError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)"
      ]
    },
    {
      "message": "Cannot read property 'defaultFieldMetadata' of null",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDatoCmsProject",
        "edges",
        4,
        "node",
        "featuredImage"
      ],
      "stack": [
        "TypeError: Cannot read property 'defaultFieldMetadata' of null",
        "    at resolve (/Users/joetaylor/Documents/www/ics/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/item/fields/file.js:32:31)",
        "    at resolveFieldValueOrError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)"
      ]
    },
    {
      "message": "Cannot read property 'defaultFieldMetadata' of null",
      "locations": [
        {
          "line": 7,
          "column": 9
        }
      ],
      "path": [
        "allDatoCmsProject",
        "edges",
        5,
        "node",
        "featuredImage"
      ],
      "stack": [
        "TypeError: Cannot read property 'defaultFieldMetadata' of null",
        "    at resolve (/Users/joetaylor/Documents/www/ics/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/item/fields/file.js:32:31)",
        "    at resolveFieldValueOrError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)",
        "    at resolveField (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:435:10)",
        "    at executeFields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:591:12)",
        "    at completeValue (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:557:21)",
        "    at completeValueCatchingError (/Users/joetaylor/Documents/www/ics/node_modules/graphql/execution/execute.js:495:19)"
      ]
    }
  ],
  "data": {
    "allDatoCmsProject": {
      "edges": [
        {
          "node": {
            "featuredImage": null
          }
        },
        {
          "node": {
            "featuredImage": null
          }
        },
        {
          "node": {
            "featuredImage": null
          }
        },
        {
          "node": {
            "featuredImage": null
          }
        },
        {
          "node": {
            "featuredImage": null
          }
        },
        {
          "node": {
            "featuredImage": null
          }
        }
      ]
    }
  }
}

**Comment by joebentaylor1995** [comment]
This has been fixed in 2.1.24
